### ISSUE TITLE
BUG: Materialdatabase or Calculation of Wood(parallel)

### ISSUE THREAD

**Issue by georglobe** [karamba3d/K3D_NightlyBuilds#25] opened 2021-01-12 14:18 UTC
**Describe the bug**
K3D 2.0.0 - build 201215 WIP for RHINO 6

Deformation wrong.

Happens with:
-Hardwood (parallel)
-Coniferous Timber (parallel)

**To Reproduce**
Change Material from (ortho) to (parallel).

**Notes**
-Upload screenshots

![Screenshot (4)](https://user-images.githubusercontent.com/68374615/104325635-25030480-54e9-11eb-9a66-14f3ec587ff0.png)
![Screenshot (5)](https://user-images.githubusercontent.com/68374615/104325655-28968b80-54e9-11eb-9524-99435d82827e.png)

-Upload a simplified version of the script (no third party grasshopper plugins)

[bug_parallel_material.zip](https://github.com/karamba3d/K3D_NightlyBuilds/files/5802630/bug_parallel_material.zip)

**Comment by Clemens-Preisinger** [comment] 2021-01-22 15:37
Hello @georglobe,
I found the cause of the strange behavior: it comes about when G12 is much smaller than E/2 which is physically not possible since it would mean that Poissons Ratio is larger than 0.5.
I have corrected the corresponding entries in the material table and set the limit of G12 to E/2. This will be part of the next WIP release
-- Clemens

**Closed by Clemens-Preisinger** 2021-01-22 15:37 UTC
Labels: bug
