### ISSUE TITLE
BUG: select elements by ID does not follow the same order of BeamForces by ID

### ISSUE THREAD

**Issue by Marco-Pellegrino** [karamba3d/K3D_NightlyBuilds#47] opened 2021-11-15 16:35 UTC
Hi @karamba3d 

I have notice a behaviour in some of the Karamba components that I wouldn't expect.
I usually need to return the forces from some elementIds and visualise them as well on Rhino Viewport.

I would think that using a regular expression i.e. &horizontal in the different components would still get the elements in the same order.
Apparently it doesn't and it could be problematic. Did you expect this behaviour?

Thanks,
Marco

![image](https://user-images.githubusercontent.com/53620289/141818175-a3dbc173-f464-4080-9e62-24f55df88ac9.png)

I have attach the file in case you want to try
https://drive.google.com/file/d/16xqtkvIHL6oCka-oTjm40Xwd3Gm3vuRZ/view?usp=sharing

**Comment by Clemens-Preisinger** [comment] 2021-11-16 11:48
Hi Marco,
thanks for your bug report.
The issue is fixed in Karamba3D 2.2.07.
-- Clemens

**Closed by Clemens-Preisinger** 2021-11-16 11:48 UTC
Labels: bug
